In [1]:
import numpy as np

In [31]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [83]:
type(a), a.shape

(numpy.ndarray, (3, 4))

In [41]:
np.zeros([1,2])

array([[0., 0.]])

In [42]:
np.zeros(2)

array([0., 0.])

In [4]:
np.ones(2)

array([1., 1.])

In [5]:
np.empty(2)

array([1., 1.])

In [6]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [7]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.ones(2, dtype=np.int64)

array([1, 1])

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [11]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
a = np.array([1, 2, 3, 4]); b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
x = np.array([[1, 2], [3, 4]]); y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim, array_example.size, array_example.shape

(3, 24, (3, 2, 4))

In [16]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [17]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
a.shape

(6,)

In [19]:
a2 = a[np.newaxis, :]
a2.shape, a2

((1, 6), array([[0, 1, 2, 3, 4, 5]]))

In [56]:
a = np.array([1, 2, 3, 4, 5, 6])
row_vector = a[np.newaxis, :]
row_vector.shape, row_vector

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

In [55]:
col_vector = a[:, np.newaxis]
col_vector.shape, col_vector

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [21]:
a

array([0, 1, 2, 3, 4, 5])

In [22]:
b = np.expand_dims(a, axis=1)
b.shape, b

((6, 1),
 array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]))

In [57]:
b = np.expand_dims(a, axis=1)
b.shape, b

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [23]:
c = np.expand_dims(a, axis=0)
c.shape, c

((1, 6), array([[0, 1, 2, 3, 4, 5]]))

In [24]:
data = np.array([1, 2, 3])
data[1], data[0:2], data[-2:]

(2, array([1, 2]), array([2, 3]))

In [25]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [27]:
a[a<6]

array([1, 2, 3, 4, 5])

In [28]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [60]:
c = a[(a > 2) & (a < 11)]
a, c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10]))

In [46]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x), x.shape, x.dtype, x[1,2]

(numpy.ndarray, (2, 3), dtype('int32'), 6)

In [48]:
y = x[:,1]
y

array([2, 5], dtype=int32)

In [49]:
y[0] = 9
y, x

(array([9, 5], dtype=int32),
 array([[1, 9, 3],
        [4, 5, 6]], dtype=int32))

In [62]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [63]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [64]:
print(a[b])

[1 2 3 4]


In [65]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [67]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])
av = np.vstack((a1, a2))
ah = np.hstack((a1, a2))
av, ah

(array([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]]),
 array([[1, 1, 3, 3],
        [2, 2, 4, 4]]))

In [68]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [70]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [71]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [72]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [73]:
b1[0] = 99
b1, a

(array([99,  2,  3,  4]),
 array([[99,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [75]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones, data - ones, data * data, data / data

(array([2, 3]), array([0, 1]), array([1, 4]), array([1., 1.]))

In [76]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [78]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0), b.sum(axis=1)

(array([3, 3]), array([2, 4]))

In [80]:
data = np.array([1.0, 2.0])
data * 1.6, data.max(), data.min(), data.sum()

(array([1.6, 3.2]), 2.0, 1.0, 3.0)

In [82]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum(), a.min(), a.min(axis=0)

(4.8595784,
 0.05093587,
 array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ]))