In [1]:
import numpy as np

In [31]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [32]:
type(a)

numpy.ndarray

In [41]:
np.zeros([1,2])

array([[0., 0.]])

In [42]:
np.zeros(2)

array([0., 0.])

In [4]:
np.ones(2)

array([1., 1.])

In [5]:
np.empty(2)

array([1., 1.])

In [6]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [7]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.ones(2, dtype=np.int64)

array([1, 1])

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [11]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
a = np.array([1, 2, 3, 4]); b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
x = np.array([[1, 2], [3, 4]]); y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [17]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
a.shape

(6,)

In [19]:
a2 = a[np.newaxis, :]
a2.shape, a2

((1, 6), array([[0, 1, 2, 3, 4, 5]]))

In [56]:
a = np.array([1, 2, 3, 4, 5, 6])
row_vector = a[np.newaxis, :]
row_vector.shape, row_vector

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

In [55]:
col_vector = a[:, np.newaxis]
col_vector.shape, col_vector

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [21]:
a

array([0, 1, 2, 3, 4, 5])

In [22]:
b = np.expand_dims(a, axis=1)
b.shape, b

((6, 1),
 array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]))

In [23]:
c = np.expand_dims(a, axis=0)
c.shape, c

((1, 6), array([[0, 1, 2, 3, 4, 5]]))

In [24]:
data = np.array([1, 2, 3])
data[1], data[0:2], data[-2:]

(2, array([1, 2]), array([2, 3]))

In [25]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [27]:
a[a<6]

array([1, 2, 3, 4, 5])

In [28]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [30]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x), x.shape, x.dtype, x[1,2]

(numpy.ndarray, (2, 3), dtype('int32'), 6)

In [48]:
y = x[:,1]
y

array([2, 5], dtype=int32)

In [49]:
y[0] = 9
y, x

(array([9, 5], dtype=int32),
 array([[1, 9, 3],
        [4, 5, 6]], dtype=int32))

In [50]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])