In [8]:
import numpy as np

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [10]:
type(a), a.shape

(numpy.ndarray, (3, 4))

In [11]:
np.zeros([1,2])

array([[0., 0.]])

In [12]:
np.zeros(2)

array([0., 0.])

In [13]:
np.ones(2)

array([1., 1.])

In [14]:
np.empty(2)

array([1., 1.])

In [15]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [16]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
np.ones(2, dtype=np.int64)

array([1, 1])

In [18]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [19]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
a = np.array([1, 2, 3, 4]); b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x = np.array([[1, 2], [3, 4]]); y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim, array_example.size, array_example.shape

(3, 24, (3, 2, 4))

In [23]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [24]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
a.shape

(6,)

In [26]:
a2 = a[np.newaxis, :]
a2.shape, a2

((1, 6), array([[0, 1, 2, 3, 4, 5]]))

In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
row_vector = a[np.newaxis, :]
row_vector.shape, row_vector

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

In [28]:
col_vector = a[:, np.newaxis]
col_vector.shape, col_vector

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [29]:
a

array([1, 2, 3, 4, 5, 6])

In [30]:
b = np.expand_dims(a, axis=1)
b.shape, b

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [31]:
b = np.expand_dims(a, axis=1)
b.shape, b

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [32]:
c = np.expand_dims(a, axis=0)
c.shape, c

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

In [33]:
data = np.array([1, 2, 3])
data[1], data[0:2], data[-2:]

(2, array([1, 2]), array([2, 3]))

In [34]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [35]:
a[a<6]

array([1, 2, 3, 4, 5])

In [36]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [38]:
c = a[(a > 2) & (a < 11)]
a, c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10]))

In [39]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x), x.shape, x.dtype, x[1,2]

(numpy.ndarray, (2, 3), dtype('int32'), 6)

In [40]:
y = x[:,1]
y

array([2, 5], dtype=int32)

In [41]:
y[0] = 9
y, x

(array([9, 5], dtype=int32),
 array([[1, 9, 3],
        [4, 5, 6]], dtype=int32))

In [42]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [43]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [44]:
print(a[b])

[1 2 3 4]


In [45]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [46]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])
av = np.vstack((a1, a2))
ah = np.hstack((a1, a2))
av, ah

(array([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]]),
 array([[1, 1, 3, 3],
        [2, 2, 4, 4]]))

In [47]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [49]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [50]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [51]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [52]:
b1[0] = 99
b1, a

(array([99,  2,  3,  4]),
 array([[99,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [53]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones, data - ones, data * data, data / data

(array([2, 3]), array([0, 1]), array([1, 4]), array([1., 1.]))

In [54]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [55]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0), b.sum(axis=1)

(array([3, 3]), array([2, 4]))

In [56]:
data = np.array([1.0, 2.0])
data * 1.6, data.max(), data.min(), data.sum()

(array([1.6, 3.2]), 2.0, 1.0, 3.0)

In [57]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum(), a.min(), a.min(axis=0)

(4.8595784,
 0.05093587,
 array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ]))

In [58]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data, data.max(axis=0), data.max(axis=1)

(array([[1, 2],
        [5, 3],
        [4, 6]]),
 array([5, 6]),
 array([2, 5, 6]))

In [59]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data, ones, data + ones


(array([[1, 2],
        [3, 4]]),
 array([[1, 1],
        [1, 1]]),
 array([[2, 3],
        [4, 5]]))

In [60]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [61]:
np.ones(3)

array([1., 1., 1.])

In [62]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.29983785, 0.97894343, 0.04487027])

In [63]:
rng.integers(5, size=(2, 4))

array([[3, 3, 1, 0],
       [0, 4, 1, 1]])

In [64]:
rng.integers(5, size=(2, 4))

array([[1, 3, 3, 3],
       [4, 3, 0, 0]])

In [65]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [66]:
unique_values, indexes_list = np.unique(a, return_index=True)
print(indexes_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [67]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [68]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [69]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
unique_rows, indexes, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
print(indexes, occurrence_count)

[0 1 2] [2 1 1]


In [72]:
data = np.array([1,2,3,4,5,6])
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
data.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [77]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [78]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [79]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [80]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [81]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [82]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [83]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [84]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [85]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [86]:
a1 = x.flatten()
a1[0] = 99
print(a1)
print(x)  # Original array

[99  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [87]:
a2 = x.ravel()
a2[0] = 98
print(a2)
print(x)   # Original array

[98  2  3  4  5  6  7  8  9 10 11 12]
[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [88]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [89]:
max?


Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method

In [90]:
a = np.array([1, 2, 3, 4, 5, 6])
a?


Type:        ndarray
String form: [1 2 3 4 5 6]
Length:      6
File:        ~/V/masterpy/lib/python3.10/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object t

In [91]:
def double(a):
  '''Return a * 2'''
  return a * 2

In [92]:
double?

Signature: double(a)
Docstring: Return a * 2
File:      /tmp/ipykernel_1251147/3639010673.py
Type:      function

In [93]:
double??

Signature: double(a)
Source:   
def double(a):
  '''Return a * 2'''
  return a * 2
File:      /tmp/ipykernel_1251147/3639010673.py
Type:      function